### PR TITLE
fix 'scale' & 'translate'

### PR DESCRIPTION
**Pull request by CodeSteak**
Hi,
Thanks for this polyfill! When I was using it, the values were a bit off. So here is a fix for scale & translate.

### CODE REVIEW

**Comment by goessner** [comment]
.. hmm ... any matrix applied later has to be multiplied from the left to current matrix .. as far as I see it .. so

```
[ sx   0  0 ]     [ a  c  e  ]     [ sx*a   sx*c    sx*e ]
[  0  sy  0 ]  *  [ b  d  f  ]  =  [ sy*b   sy*d    sy*f ]
[  0  0   1 ]     [ 0  0  1  ]     [    0      0     1   ]
```

in case of scaling. Translation is similar. So please, if in doubt,  raise an issue first before a pull request.

Cheers

**Comment by CodeSteak** [comment]
**Update**:  The math is 
scale:
```
[ a  c  e ]     [sx  0  0 ]     [ a*sx  c*sy  e  ]
[ b  d  f ]  *  [  0 sy 0 ]  =  [ b*sx  d*sy  f  ]
[ 0  0  0 ]     [  0  0 1 ]     [   0     0   1  ]
```
translate:
```
[ a  c  e ]     [ 1  0  x ]     [ a c e+a*x+c*y  ]
[ b  d  f ]  *  [ 0  1  y ]  =  [ b d f+b*x+d*y  ]
[ 0  0  0 ]     [ 0  0  0 ]     [ 0 0       1    ]
```
______

See #2 

to verify please run:

```html
<body onload="init()">
<canvas width="200" height="200" id="canvas"></canvas>
<script>
// Copy pasted from fix repo
Object.defineProperty(CanvasRenderingContext2D.prototype, "currentTransform", {
   get : function() { return this._t2stack && this._t2stack[this._t2stack.length-1] || {a:1,b:0,c:0,d:1,e:0,f:0}; },
   set : function(x) {
      if (!this._t2stack)
         this._t2stack = [{}];
      this._t2stack[this._t2stack.length-1] = {a:x.a,b:x.b,c:x.c,d:x.d,e:x.e,f:x.f};
   },
   enumerable : true,
   configurable : false
});
CanvasRenderingContext2D.prototype.resetTransform = function() {
   var resetTransform = CanvasRenderingContext2D.prototype.resetTransform;
   return function() {
      if (!this._t2stack)
         this._t2stack = [{}];
      this._t2stack[this._t2stack.length-1] = {a:1,b:0,c:0,d:1,e:0,f:0};
      resetTransform && resetTransform.call(this);
   }
}();
CanvasRenderingContext2D.prototype.scale = function() {
   var scale = CanvasRenderingContext2D.prototype.scale;
   return function(sx,sy) {
      if (!this._t2stack)
         this._t2stack = [{a:1,b:0,c:0,d:1,e:0,f:0}];
      var t = this._t2stack[this._t2stack.length-1];
      sx = sx || 1;
      sy = sy || sx;
    //updated:
      t.a *= sx; t.c *= sx;
      t.b *= sy; t.d *= sy;
      scale.call(this,sx,sy);
   }
}();
CanvasRenderingContext2D.prototype.translate = function() {
   var translate = CanvasRenderingContext2D.prototype.translate;
   return function(x,y) {
      if (!this._t2stack)
         this._t2stack = [{a:1,b:0,c:0,d:1,e:0,f:0}];
      var t = this._t2stack[this._t2stack.length-1];
      //updated:
       t.e += x*t.a + y*t.c;
       t.f += x*t.b + y*t.d;
      return translate.call(this,x,y);
   }
}();
</script>
<script>
function translateCoords(m,x,y){
  // I hope I have no error in  here
  let nx = x*m.a + y*m.c + m.e;
  let ny = x*m.b + y*m.d + m.f;
  return [nx, ny]
}

function init(){
  var ctx = canvas.getContext("2d");
  ctx.resetTransform();
  // Some random sclaing and translating
  ctx.translate(10,10);
  ctx.scale(20,20);
  ctx.translate(2,2);
  ctx.scale(1.1,1.1);
  ctx.fillStyle = "red"
  ctx.fillRect(0,0,1,1);
  var pixelCoordsTopLeft = translateCoords(ctx.currentTransform, 0,0);
  var pixelCoordsBottomRight = translateCoords(ctx.currentTransform, 1,1);

  // reset to normal
  ctx.resetTransform();

  //draw on the calculated pixels
  ctx.fillStyle = "blue";
  ctx.fillRect(pixelCoordsTopLeft[0],pixelCoordsTopLeft[1],
    pixelCoordsBottomRight[0]-pixelCoordsTopLeft[0],
    pixelCoordsBottomRight[1]-pixelCoordsTopLeft[1]);
}
</script>
</body>
```

**Comment by CodeSteak** [comment]
I also fixed rotate and transform. Same Issue: Matrix multiplication was in wrong order. :grimacing:

**Comment by goessner** [comment]
Hi,
you are obviously right ... this is ... really strange, as it seems to be completely agains the common rules of vector algebra. Usually in Kinematics and Robotics transform matrices are always written with respect to the global (fixed) coordinate system.

See [here](https://en.wikipedia.org/wiki/Transformation_matrix) or [here](https://math.stackexchange.com/questions/384804/combine-transformation-matrices).

Obviously subsequent transformations are relative to the current transformed coordinate system with canvas, which is  unusual even in computer graphics. I simply was not aware of that, as I most often calculate my matrix first and inject it using `setTransform`.

I need to compare the results with `mozCurrentTransform` and `webkitCurrentTransform`, which I was sure having done correctly in the past. But I do not doubt, that your results are correct .. just to be sure.

Unfortunately I won't have time to do that for the next two weeks .. maybe you are willing to do that proof meanwhile.

Thanks for your effort

Stefan

**Comment by CodeSteak** [comment]
Thanks for that detailed response. :smile:

I will write a randomized test against `mozCurrentTransform` and put it in a `test` folder in the repo within the next few day.

Happy Easter!

**Comment by CodeSteak** [comment]
The test is done (only runs on Firefox). It shows the maximum `difference / avg` in percent of each individual element of the matrix after making some random calls. 
Every 10 calls the transform matrix gets reset to prevent error propagation. 

Also, I noticed that `scale` was still wrong, so I finally fixed it.

**Comment by CodeSteak** [comment]
Hi, 
are there any news?

**Pull request merged**
